FROM docker.io/ubuntu:noble

RUN set -exu \
  && export DEBIAN_FRONTEND=noninteractive \
  && apt-get -yq update \
  && apt-get -yq dist-upgrade \
  && apt-get -yq install \
    --no-install-recommends \
      alsa-utils \
      bind9-dnsutils \
      ca-certificates \
      coreutils \
      curl \
      dbus \
      dbus-x11 \
      expect-dev \
      fastfetch \
      firefox-esr \
      gettext-base \
      gnome-remote-desktop \
      iproute2 \
      iputils-ping \
      jq \
      libgl1-mesa-dri \
      locales \
      mesa-utils \
      mingetty \
      nano \
      net-tools \
      openssl \
      paprefs \
      pavucontrol \
      pulseaudio \
      socat \
      sudo \
      supervisor \
      tigervnc-standalone-server \
      tzdata \
      udev \
      vim \
      wget \
      xwayland \
      xwayland-run \
      xwaylandvideobridge \
      xz-utils \
      yq

RUN set -exu \
  && mkdir -pv /var/log/supervisor \
  && chmod 777 /var/log/supervisor

COPY rootfs /

RUN set -exu \
  && export DEBIAN_FRONTEND=noninteractive \
  && export DEBEMAIL="pers.edwin@gmail.com" \
  && mkdir -pv /grd-build/ || true \
  && cd /grd-build/ || exit 1 \
  && wget https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/gnome-remote-desktop/46.3-0ubuntu1/gnome-remote-desktop_46.3.orig.tar.xz            --output-document=/grd-build/gnome-remote-desktop_46.3.orig.tar.xz \
  && wget https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/gnome-remote-desktop/46.3-0ubuntu1/gnome-remote-desktop_46.3-0ubuntu1.dsc           --output-document=/grd-build/gnome-remote-desktop_46.3-0ubuntu1.dsc \
  && wget https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/gnome-remote-desktop/46.3-0ubuntu1/gnome-remote-desktop_46.3-0ubuntu1.debian.tar.xz --output-document=/grd-build/gnome-remote-desktop_46.3-0ubuntu1.debian.tar.xz \
  && tar xvf gnome-remote-desktop_46.3.orig.tar.xz \
  && tar xvf gnome-remote-desktop_46.3-0ubuntu1.debian.tar.xz \
  && ln -s gnome-remote-desktop_46.3.orig.tar.xz gnome-remote-desktop_46.3-1-kubevda.orig.tar.xz \
  && mv debian gnome-remote-desktop-46.3/ \
  && cd gnome-remote-desktop-46.3/ \
  && for patch in /grd-build/patches/*.patch; do \
        patch -p1 --forward < $patch || true; \
      done \
  && mk-build-deps --tool "apt-get -yq -o Debug::pkgProblemResolver=yes --no-install-recommends" -ir "/grd-build/gnome-remote-desktop-48.0/debian/control" \
  && dch --preserve --local "-kubevda-" "build with VNC support for kubevda" \
  && DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -uc -us \
  && dpkg -i /grd-build/gnome-remote-desktop_46.3-1-kubevda-1_amd64.deb \
  && dpkg -P gnome-remote-desktop-build-deps \
  && apt-get -yq clean \
  && apt-get -yq autoremove

CMD ["/bin/bash", "/entrypoint.sh"]
